### ISSUE TITLE
wish: more complete readme

### ISSUE THREAD

**Issue by markstos** [faceair/mongoose-inserter#1]
Please sample syntax and basic method descriptions to the README.

**Comment by faceair** [comment]
Oh, i delete my reply accidentally just now.

I create that to init mongodb for test.
If you just want to know how to use it, you can see [https://github.com/faceair/mongoose-inserter/blob/master/test.coffee](https://github.com/faceair/mongoose-inserter/blob/master/test.coffee), it's easy to understand.
And i will add README as soon as possible, thanks for your suggestion.
